# This file contains values from Cookiecutter

default_context:
  project_name: "ckan-client-tacc"
  project_description: "Awesome `ckan-client-tacc` is a Python cli/package created with https://github.com/Undertone0809/python-package-template"
  organization: "In-For-Disaster-Analytics"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "in_for_disaster_analytics"
  email: "maxiosorio@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
